export const LOAD_SERVICES = 'LOAD_SERVICES';
export const LOAD_CURRENT_SERVICE = 'LOAD_CURRENT_SERVICE';
export const LOAD_SERVICES_SUCCESS = 'LOAD_SERVICES_SUCCESS';
export const LOAD_SERVICES_FAILED = 'LOAD_SERVICES_FAILED';
export const LOAD_CURRENT_SERVICE_SUCCESS = 'LOAD_CURRENT_SERVICE_SUCCESS';
export const LOAD_CURRENT_SERVICE_FAILED = 'LOAD_CURRENT_SERVICE_FAILED';